### ISSUE TITLE
ensure synthetics verify SSL mode is enabled for MozMEAO sites

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#1047]
- basket.mozilla.org
- careers.mozilla.org
- snippets.mozilla.com
- do we want snippets.cdn.mozilla.net in here as well, it's managed by IT

**Comment by jgmize** [comment]
For context, the "verify SSL" checks in NR synthetics were originally disabled due to an unacceptable rate of false alarms. Based on the discussion in https://discuss.newrelic.com/t/verify-ssl-doesnt-work/28034/24 some of these reliability issues may be resolved by re-creating the checks so that a newer version of the openssl s_client is used in the check (see https://docs.newrelic.com/docs/synthetics/new-relic-synthetics/using-monitors/add-edit-monitors#simple for more details).

**Comment by metadave** [comment]
ah, right. Is this something that Neres can do for us automatically?

**Comment by jgmize** [comment]
yes, I believe this could be scripted with [neres](https://github.com/glogiotatidis/neres).

**Comment by bensternthal** [comment]
This looks to have been marked complete.
