### ISSUE TITLE
Chrome CORS issue on https://assets.mozilla.net/fonts/FirefoxSharpSans-Medium.woff2

### ISSUE THREAD

**Issue by jgmize** [mozmeao/infra#1118]
- https://bedrock-demo-craigcook.oregon-b.moz.works/en-US/firefox/accounts/ gives a `Access to font at 'https://assets.mozilla.net/fonts/FirefoxSharpSans-Medium.woff2' from origin 'https://bedrock-demo-craigcook.oregon-b.moz.works' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource` in the dev console on chrome

- https://serverfault.com/a/856948  explains why this is happening and several workarounds

**Comment by metadave** [comment]
@craigcook what project is this related to?

**Comment by craigcook** [comment]
> @craigcook what project is this related to?

It was originally related to the redesigned accounts page, but I subsequently removed the font from that page because it will be formally arriving with the next version of Protocol any day now (see https://github.com/mozilla/bedrock/pull/7227). 

I don't know if this will still be relevant but suspect it might be... I'm looking at https://bedrock-demo-protocol.oregon-b.moz.works in Chrome and seeing no CORS errors, BUT I'm also not seeing any pages using Sharp Sans Medium (which is what triggered the issue), only Bold (which didn't). So this may still warrant further investigation and testing in case it manifests again.

**Comment by jgmize** [comment]
This issue currently blocks mozilla/bedrock#7227, but I'm not going to prioritize implementing workarounds for this incompatibility with our existing open source software, deployment, and build systems, because that would mean saying no to other priorities. Instead, I'm going to say no to this font. While I'm sure the original decision to move forward with this font was made with best intentions, this is ultimately an engineering decision, and I believe it is fundamentally at odds with our open source values and with the Mozilla mission. I am opposed to including "Firefox Sharp Sans" or any other proprietary font in our websites or in our products.
