### ISSUE TITLE
basket-dev oregon-a ELB issues

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#1146]

**Comment by jgmize** [comment]
The reason none of the oregon-a nodes were showing up as "in service" on the basket-dev ELB was because the http healthchecks to the nodeport service were failing due to a failure of the `ALLOWED_HOSTS` setting to propagate from Deis Workflow to the generated k8s deployment, which we missed when we created [the new deployment based on it](https://github.com/mozmeao/basket-config/blob/e894a8537794fd6bfaef6325d3e7f71b27b9fa83/oregon-a/basket-dev/worker-deploy.yaml).
