### ISSUE TITLE
troubleshoot SystemExits in Frankfurt for most (all?) apps

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#1182]

**Comment by jgmize** [comment]
I [upgraded this cluster](https://github.com/mozmeao/infra-private/pull/226) early this morning, and [according to our logs](https://my.papertrailapp.com/events?q=systemexit) the last SystemExit was before the upgrade ([Nov 05 05:14:58 UTC](https://my.papertrailapp.com/groups/1644803/events?focus=1128331847005802529&q=systemexit&selected=1128331847005802529)), but the previous one was several hours before that ([Nov 04 18:37:33 UTC](https://my.papertrailapp.com/groups/1644803/events?focus=1128171436683526152&q=systemexit&selected=1128171436683526152)) so we will wait at least 24-48 hours before calling this "fixed", and even if the problem doesn't recur it's still possible that the root cause was intermittent networking issues as I originally suspected rather than me reprovisioning all of nodes as part of a cluster upgrade.

**Comment by jgmize** [comment]
Correction to my previous comment: the last time we saw a SystemExit error in the logs *in frankfurt* was ([Nov 04 18:37:33 UTC](https://my.papertrailapp.com/groups/1644803/events?focus=1128171436683526152&q=systemexit&selected=1128171436683526152)) and before that was [Nov 04 15:44:28 UTC](https://my.papertrailapp.com/groups/1644803/events?focus=1128127877100032001&q=systemexit&selected=1128127877100032001). While we still haven't seen a SystemExit in frankfurt today, we saw a few from iowa-a and oregon-b.
