### ISSUE TITLE
MDN: persistent k8s dev env

### ISSUE THREAD

**Issue by jgmize** [mozmeao/infra#134]
- Phase 1: maintenance mode
  - RO DB
    - [X] Docs PR on installing mysql helm chart with persistence enabled
      - initially using https://github.com/mdn/helm-charts/tree/master/mysql
        - PR: https://github.com/mozmar/infra/pull/135
      - will try to use upstream https://github.com/kubernetes/charts/tree/master/stable/mysql later by either getting a PR merged or by implementing the custom collation without a custom image & chart
  - memcached
    - [X] https://github.com/mozmar/infra/pull/149
  - deploy Kuma web pods via Jenkinsfile, j2, and `kubectl apply`
    - [X] #191 
      - [ ] with EFS PVCs: #183 
  - no kumascript
  - no elasticsearch
- Phase 2: full RW dev env
  - all productions services and capabilities
  - [ ] deploy on each merge to master
    - [ ] kuma
    - [ ] kumascript
  - [ ] run integration tests after each deployment
  - [ ] https

**Comment by jwhitlock** [comment]
It will require additional work (1 week?) in Kuma to eliminate the need for workers in maintenance mode.  It's used by the cacheback tasks to populate things like the contributor bar that take too long to generate synchronously.

I'm not sure why you are trying to eliminate elastic search for maintenance mode - it doesn't require a writable database.

**Comment by jgmize** [comment]
@jwhitlock disabling search in maintenance mode simplifies phase 1 a bit, but we plan on having it in phase 2, which is still in Q2. If you think we need elasticsearch in phase 1 though I'd be happy to discuss further.

**Comment by jgmize** [comment]
@jwhitlock would disabling the contributor bar entirely in maintenance mode add or subtract from your 1 week estimate?

**Comment by jwhitlock** [comment]
I'd rather have @escattone's estimate - he went through each async task to evaluate it for maintenance mode, and would have a better idea about the work involved.

**Comment by escattone** [comment]
Thanks @jwhitlock, I was just starting to write this when your last comment arrived. Currently in maintenance mode, we allow only three celery tasks:
- ``kuma.humans.tasks.humans_txt`` -- generates the ``humans.txt`` file (list of contributors to MDN)
- ``kuma.wiki.tasks.build_sitemaps`` -- builds/saves sitemap files for every MDN language, and builds/saves a sitemap index file as well (this in turn, calls two other celery tasks: ``kuma.wiki.tasks.build_locale_sitemap`` and ``kuma.wiki.tasks.build_index_sitemap``)
- ``cacheback.tasks.refresh_cache`` -- in the end, this boils down to only one task in maintenance mode (all others are blocked or fetch synchronously on a cache miss), and that is the ``DocumentContributorsJob`` which is called for every document endpoint

I can't see in the kuma repo where the first two are ever used/called (am I missing something @jwhitlock?), so it seems we don't need to worry about those? For the document contributors, if we disabled the contributor bar, it would be a very small amount of work (a couple of hours work at most assuming added tests as well)

We could also simply set ``CELERY_ALWAYS_EAGER=True``. Of course, the initial document view response may be slowed a bit since it will populate the "contributors" cache synchronously, but subsequent responses would hit the populated cache, and that cache would never be invalidated since we don't allow document edits.

**Comment by jgmize** [comment]
I'd rather avoid setting `CELERY_ALWAYS_EAGER=True`.

**Comment by jgmize** [comment]
If we're talking about a couple of hours work to disable the contributors bar and those other tasks in maintenance mode, I think it would be worth it. @escattone would you be willing to work on that on whatever schedule fits best with your other work?

**Comment by escattone** [comment]
Absolutely @jgmize, I'll take care of that.

**Comment by jwhitlock** [comment]
The additional tasks ``humans_txt``, ``build_sitemaps``, etc. are scheduled in the database as periodic tasks in the [Django admin](https://developer.mozilla.org/admin/djcelery/periodictask/).  They rely on the ``celerybeat`` service running, which adds them to the queue as scheduled. I don't think we've made plans to run the ``celerybeat`` or ``celerycam`` services in AWS.

**Comment by escattone** [comment]
I was just re-reading this thread and realized a misunderstanding. My estimate of an hour of work was only for disabling the contributors bar, not the other two tasks that @jwhitlock mentions above. I'm not sure yet how best to tackle those.

**Comment by jgmize** [comment]
Since `humans_txt` and `build_sitemaps` generate files and the data used to generate these files won't be changing in maintenance mode, there's no need to schedule them to run periodically for that case. Let's plan on handling those files similar to the way we will handle user uploads.

**Comment by jgmize** [comment]
As for `celerybeat` and `celerycam`, we'll set those up in phase 2 along with the rest of the services expected for a full RW environment. I

**Comment by jgmize** [comment]
I do not think we need to run the `refresh_cache` task in maintenance mode, as the data will not be changing so there will not be anything to update. I do not believe any code or other settings changes should be necessary for this, based on my understanding of django-cacheback.

**Comment by escattone** [comment]
@jgmize Yeah, once I update the code so that we don't get the document contributors in maintenance mode, the ``cacheback.tasks.refresh_cache`` celery task will never be called.

Yesterday, @jwhitlock and I discussed a pre-deploy step for maintenance mode where we can accomplish some one-time setup tasks (like the ``humans_txt`` and ``build_sitemaps`` tasks). In light of that, it seems it would make sense to create scripts/Django-management-commands to handle the ``humans_txt`` file and ``build_sitemaps`` tasks?

I'm going to start work right now on a PR for this stuff.

**Comment by jgmize** [comment]
For file persistence we are currently experimenting with EFS (see https://github.com/mozmar/infra/issues/183) which requires a different approach than we are currently using for the ephemeral demo deployments: specifically, we can't use Deis Workflow to manage the Kuma deployments and will need to either use `kubectl apply` or helm. @escattone and I are currently working on this in the [mdn-dev](https://github.com/mozmar/infra/compare/mdn-dev) branch.

**Comment by escattone** [comment]
@jgmize and I worked on pushing this forward for several hours on Friday:
- added [Jenkins multi-branch pipeline for infra](https://ci.us-west.moz.works/blue/organizations/jenkins/infra/activity)
- added [``Jenkinsfile``](https://github.com/mozmar/infra/blob/mdn-dev/Jenkinsfile) (copied from [Kuma](https://github.com/mozilla/kuma/blob/master/Jenkinsfile) -- note use of ``.yaml`` rather than ``.yml``) and [``Jenkinsfiles/mdn-dev.groovy``](https://github.com/mozmar/infra/blob/mdn-dev/Jenkinsfiles/mdn-dev.groovy)
- added stages to ``Jenkinsfiles/mdn-dev.groovy`` for both Virginia and Tokyo clusters

Next steps:
- replace ``helm install``'s of ``memcached`` and ``mysql`` with Jinja2-templated Kubernetes configuration files (which we may generate initially via ``helm install --dry-run --debug ...``)
- add EFS work from #183 to ``mdn-dev.yaml.jinja``

**Comment by jgmize** [comment]
for phase 2 elasticsearch, I'm leaning towards the self-hosted option for the dev env, but one of the hosted options for staging & prod. See #193 for more details

**Comment by jgmize** [comment]
@escattone and @metadave have been working on this in https://github.com/mozmeao/infra/pull/360

**Comment by jwhitlock** [comment]
If this happens, it will happen after operations has moved out of MozMEAO. Closing for now.
