### ISSUE TITLE
New architecture for release notes

### ISSUE THREAD

**Issue by jgmize** [mozmeao/infra#185]
- [ ] move templates from [bedrock](https://github.com/mozilla/bedrock/tree/master/bedrock/firefox/templates/firefox/releases) to [rna](https://github.com/mozilla/rna)
- [ ] add feature to rna: generate release notes static html
- [ ] add features to [nucleus](https://github.com/mozilla/nucleus)
  - [ ] add a "preview" button that uses rna to generate static html and redirects to the generated page
  - [ ] add a button or admin action that submits a PR to a new repo, say, mozilla/release-notes
    - [ ] user is then redirected to PR on github where they can request a review or merge it themselves if they have commit access
  - generated html could also be published on https://mozilla.github.io/release-notes as a "staging" site for release notes
- use generated html via one of the options below (or maybe something better :)
  - option 1: monolith
    - [ ] create a shallow clone of the new release-notes repo during bedrock docker image build
    - [ ] serve files with django whitenoise
  - option 2: microservice
    - [ ] use a separate service with nginx containers to serve redirects and the generated files
    - [ ] route traffic matching releasenotes url pattern using an [ingress](https://kubernetes.io/docs/concepts/services-networking/ingress/) [controller](https://github.com/kubernetes/ingress) https://github.com/mozmar/infra/issues/187

**Comment by jgmize** [comment]
@pmclanahan @glogiotatidis what are your thoughts?

**Comment by pmac** [comment]
This would mean that we still have to run and maintain Nucleus. I thought one of the big problems we wanted to solve was to get out of that business. If we're going to move to static files I'd like to go all in on that and just have it be a github repo with a static site generator like Lektor (or whatever else). Jenkins could build and push back to a `gh-pages` branch for preview for them, and they could push to a `prod` branch to make it live. I don't think going to static files just for the server-side advantages is worth it. We're not having performance issues.

As for deployment I'm still conflicted. I see a lot of advantages to a microservices architecture but worry about maintainability. If we copy the templates and CSS from bedrock they'll quickly grow outdated. If we create a central repo for hosting base templates and CSS then that'll get hard to update due to differing use in the services. Also we'd be creating a lot of different CSS bundles with the same stuff in them but without the cache advantage unless we rely on whatever bedrock core has deployed. And if we split static media into it's own repo and service then deployment timing will be a nightmare. I'm just really struggling with the efficiency gains for the servers vs. for the developers.

**Comment by jgmize** [comment]
Thanks for your thoughtful reply @pmac. To be clear, I do want to get rid of nucleus *as it exists today*, but I do see some value in a browser-based editing environment for users that don't want to install anything locally and/or are not comfortable with using git from the command line. Lektor is one of several existing systems that we could potentially adapt for this purpose, but it seems to me that it might be easier to add static html generation to the existing codebase, leveraging the existing models and templates.

**Comment by jgmize** [comment]
One of the other options that I looked into was https://www.netlifycms.org/ which looks like a great open source solution except for one thing: it requires write access to all public repos on your github account. My proposal to have the editor generate a PR instead of committing directly adds an extra step for the user, but this way the web service only needs a "robot account" with commit access to its own fork, and we don't have to deal with any oauth dance to commit on behalf of the user since they can just click the merge button in the github interface directly.

**Comment by pmac** [comment]
I do really like Netflify. I'm guessing the server side of netlify isn't something we can self host?

But to the broader point I really want to stop supporting Nucleus. I'd rather just keep syncing the DB data if we're going to have to keep and maintain Nucleus.

**Comment by jgmize** [comment]
Yes, we can absolutely self-host netlify-cms: https://github.com/netlify/netlify-cms and indeed my first thought when I started investigating it was to deprecate the current nucleus code base entirely and host netlify-cms at https://nucleus.mozilla.org/admin, but for the reasons I outlined in my previous comments I proposed this more conservative approach, thinking that once we had all the other pieces in place it would be easier to replace the admin later.

**Comment by pmac** [comment]
I mean the Netlify service that the /admin page talks to. That's the thing to which you have to give control of your repos. If we hosted that bit and were the keeper of those keys I'd be much less concerned.

**Comment by jgmize** [comment]
@pmac: the /admin page doesn't need to talk to a netlify service at all: the backend is github. If you'd rather jump straight to netlify-cms, skipping the intermediate conservative steps I outlined, I personally have no objections but the current users may have other preferences. What do you think about putting together a netlify-cms release notes PoC demo and requesting feedback on the interface & workflow?

**Comment by pmac** [comment]
I'd love to play with it. I'll add that to my TODOs.
