### ISSUE TITLE
Ingress controller evaluation

### ISSUE THREAD

**Issue by jgmize** [mozmeao/infra#187]
- https://kubernetes.io/docs/concepts/services-networking/ingress/
- https://github.com/kubernetes/ingress
- https://github.com/kubernetes/ingress/blob/master/docs/catalog.md
- https://github.com/kubernetes/ingress/blob/master/examples/README.md

**Comment by jgmize** [comment]
https://medium.com/@cashisclay/kubernetes-ingress-82aa960f658e

**Comment by metadave** [comment]
- https://medium.com/@patrickeasters/using-traefik-with-tls-on-kubernetes-cb67fb43a948
- https://getkong.org/

**Comment by jgmize** [comment]
Blocks #448

**Comment by metadave** [comment]
https://www.getambassador.io/

**Comment by metadave** [comment]
See https://github.com/mozmeao/infra-private/pull/132

**Comment by metadave** [comment]
https://github.com/appscode/voyager

**Comment by metadave** [comment]
### The Problem

Bedrock currently uses a [git-push based method for deploying demo branches](https://github.com/mozilla/bedrock/blob/ad71a2eac618e4b12aac7825e38bdab7a7f2eb5d/docs/contribute.rst#server-architecture) to dynamic subdomains of moz.works with TLS support. 
For example, pushing a git branch named `demo/feature` would create a demo instance with the following URL: `https://bedrock-demo-feature.us-west.moz.works/`.

This feature is provided by the Deis Workflow router, which is now officially unsupported. To replace the functionality that Deis Workflow provides, we need a custom Kubernetes Ingress that can route traffic from a dynamic domain name to a Kubernetes deployment with TLS. Our evaluation has been primarily performed in [GCP](https://cloud.google.com/) with [GKE](https://cloud.google.com/kubernetes-engine/). 

We'd also like to gain experience using [Kubernetes Ingress](https://kubernetes.io/docs/concepts/services-networking/ingress/) and learn how it can help solve some of our infrastructure problems.


### Requirements

In our evaluation, we looked for the following features:

- easy to setup, configure and maintain
    - SRE should spend no more than a few hours installing and understanding how the product works
- the product must provide comprehensive and up-to-date documentation
- the ability to dynamically route to new K8s deployments based on domain name (rather than /path)
- LetsEncrypt certificate request and auto-renewal support
   - it's preferrable to use ACME cert validation with Route53
       - .moz.works / .mozmar.org domains are hosted in AWS Route53, the product should be able to easily update hosted zones a with appropriate credentials
       - ACME http validation may require application request path modifications
   - bonus: automatically request LetsEncrypt wildcard certificates

### Evaluation

This section contains notes on products that were evaluated:

- [Ambassador](https://www.getambassador.io/)
    - the demo application failed to route traffic every few requests under extremely _low_ load conditions.
    - no LetsEncrypt integration, TLS [is setup manually](https://www.getambassador.io/user-guide/tls-termination)
        - manual cert renewal


- [Traefik](https://traefik.io/)
    - Traefik is a general solution that supports many backends, including K8s, Docker, ECS, Mesos, Zookeeper etc.
    - poor Kubernetes installation documentation
        - I had to dig through [blog post](https://medium.com/@patrickeasters/using-traefik-with-tls-on-kubernetes-cb67fb43a948)s and Github issues to figure out how to install in K8s
    - Traefik supports Let's Encrypt, however the [documentation is limited](https://docs.traefik.io/configuration/acme/).
    - I was unable to get Traefik up and running after 1.5 days (_without_ TLS/LetsEncrypt support) 


- [Nginx Ingress Controller](https://kubernetes.github.io/ingress-nginx/)
    - from the docs: It is built around the Kubernetes Ingress resource, using a ConfigMap to store the NGINX configuration.
    - [TLS is supported](https://kubernetes.github.io/ingress-nginx/user-guide/tls/) with [kube-lego](https://github.com/jetstack/kube-lego), which states:

            kube-lego is in maintenance mode only. There is no plan to support any new features. 
            The latest Kubernetes release that kube-lego officially supports is 1.8. The officially 
            endorsed successor is cert-manager.
        
    - kube-lego's successor is [cert-manager](https://github.com/jetstack/cert-manager/), which states the following in it's readme:
    
            This project is not yet ready to be a component in a critical production stack, 
            however it is at a point where it offers comparable features to other projects 
            in the space. If you have a non-critical piece of infrastructure, or are feeling 
            brave, please do try cert-manager and report your experience here in the issue section.
    - given that the two above certificate management solutions aren't suitable for production, we moved on to other products.    


- [Heptio Contour](https://github.com/heptio/contour)
    - From the readme: 

            This is an early release so that we can start sharing with the community.
    - [cert support](https://github.com/heptio/contour/blob/master/docs/cert-manager.md) is via [cert-manager](https://github.com/jetstack/cert-manager/), which states that it's not ready for production use.


- [GKE Ingress](https://cloud.google.com/kubernetes-engine/docs/tutorials/http-balancer) + Certsbridge
    - no LetsEncrypt support, however we successfully uploaded a manually-request LetsEncrypt wildcard certificate via the GUI.
    - Certsbridge is a GCP product (made by Google)
        - it currently does not support wildcard certificates
        - a cert can only have a single name (it does not support Subject Alternative Names)
        - Certsbridge is currently in alpha
        - we are also evaluating Certsbridge for use with GKE-hosted prod/stage/dev environments
            - certificates in this case would be for Cloudflare to load balancer communications. 


- [Voyager](https://appscode.com/products/voyager/)
    - out of all ingress controllers evaluated, this was the easiest to get up and running with TLS and dynamic routing
    - LetsEncrypt support is per-namespace
        - for example, bedrock-demo needs it's own LetsEncrypt config and requested certs are placed in this namespace
    - LetsEncrypt wildcard support added in 7.0.0, which was released a few days ago
    - uses K8s CustomResourceDefinitions (a custom Ingress object)
    - Voyager uses [HAProxy](https://www.haproxy.org/) under the hood
        - configurable number of HA proxy pods per Ingress
    - Route53 LetsEncrypt verification
    - certs are automatically [renewed 7 days before expiration](https://appscode.com/products/voyager/7.0.0/guides/certificate/faq/#how-do-i-renew-my-le-certificates)
    - Voyager uses an IAM account to manage a Route53 hosted zone. For security, we prefer to use a hosted zone other than `moz.works`. Testing was performed with `mozmar.org`.
    - it takes < 1 minute for a new host to appear after being added to the ingress.

### Recommendation

Voyager was the easier product to setup that met all of our requirements. A wildcard certificate per ingress seems to be the easiest way to dynamically host bedrock demo instances.

**Comment by metadave** [comment]
cc @bensternthal ^

**Comment by bensternthal** [comment]
Got it.. thanks for the explanations!
