### ISSUE TITLE
migrate MDN Apache Alias rules

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#241]
The following rewrites and aliases will have to be accounted for in Kuma:

```
# Links to FTP'ed code samples and examples
RewriteRule ^patches(.*) data/www/patches$1 [L]
RewriteRule ^presentations(.*) data/www/presentations$1 [L]
RewriteRule ^samples(.*) data/www/samples$1 [L]
RewriteRule ^diagrams(.*) data/www/diagrams$1 [L]
RewriteRule ^web-tech(.*) data/www/web-tech$1 [L]
RewriteRule ^css(.*) data/www/css$1 [L]

# Rewrites to robots & sitemaps
RewriteRule ^robots.txt$ media/robots.txt [L]
RewriteRule ^sitemap.xml$ media/sitemap.xml [L]
RewriteRule ^sitemaps/([\w\-]*)/sitemap.xml$ media/sitemaps/$1/sitemap.xml [L]

mozilla/domains/developer.cdn.mozilla.net.conf
28:    Alias /media /data/www/developer.mozilla.org/kuma/media
29:    Alias /admin-media /data/www/developer.mozilla.org/kuma/vendor/src/django/django/contrib/admin/media

conf/httpd.conf
561:Alias /icons/ "/var/www/icons/"
873:Alias /error/ "/var/www/error/"

conf/httpd.conf.rpmnew
551:Alias /icons/ "/var/www/icons/"
576:ScriptAlias /cgi-bin/ "/var/www/cgi-bin/"
855:Alias /error/ "/var/www/error/"

mozilla/domains/developer.mozilla.org.conf
72:    Alias /media /data/www/developer.mozilla.org/kuma/media
73:    Alias /admin-media /data/www/developer.mozilla.org/kuma/vendor/src/django/django/contrib/admin/media
75:    Alias /presentations /data/www/presentations
76:    Alias /samples /data/www/samples
77:    Alias /diagrams /data/www/diagrams
90:    WSGIScriptAlias /mwsgi /data/www/developer.mozilla.org/kuma/wsgi/kuma.wsgi
```

[parent issue](https://github.com/mozmar/infra/issues/147)

**Comment by metadave** [comment]
@jwhitlock @jgmize @escattone Are these best handled by whitenoise?

**Comment by jwhitlock** [comment]
😢 

Many of these are Apache-only and can be ignored.  Some could be served by Whitenoise, but shouldn't, because it will slow down engine startup while Whitenoise calculates hashes for very large, seldom-accessed files.  Others are dynamically created and Whitenoise says [it is a bad idea to serve them](http://whitenoise.evans.io/en/stable/django.html#serving-media-files).

I'm not sure what the best option is. Maybe redirect all these file-serving URLs to https://mdn.mozillademos.org/ or developer.cdn.mozilla.net, and run nginx there?

Details:

* ``RewriteRule ^patches(.*) data/www/patches$1 [L]`` - No such files in production, can ignore
* ``RewriteRule ^presentations(.*) data/www/presentations$1 [L]`` - PDFs, videos, and slides from 2005 - 2009, no new ones expected. I eventually want to redirect to S3 or similar, Django / Whitenoise is OK for now.
* ``RewriteRule ^samples(.*) data/www/samples$1 [L]`` - Demonstration code from 2005 - 2012, no new ones expected.  There was a project around 2015 to redirect these to current MDN pages and examples. Django / Whitenoise is OK for now.
* ``RewriteRule ^diagrams(.*) data/www/diagrams$1 [L]`` - What was someone's idea of the Mozilla workflow in 2010? [Now you know](https://developer.mozilla.org/diagrams/workflow/workflow.svg). Django / Whitenoise is OK.
* ``RewriteRule ^web-tech(.*) data/www/web-tech$1 [L]`` - No such files in production, can ignore
* ``RewriteRule ^css(.*) data/www/css$1 [L]`` - No such files in production, can ignore
* ``RewriteRule ^robots.txt$ media/robots.txt [L]`` - This needs to be re-written as a Django view, because it is different in [production](https://developer.mozilla.org/robots.txt) and [staging](https://developer.allizom.org/robots.txt).
* ``RewriteRule ^sitemap.xml$ media/sitemap.xml [L]`` - Generated by a periodic task.  Whitenoise is not appropriate for generated files, may have to be a Django view or other.
* ``RewriteRule ^sitemaps/([\w\-]*)/sitemap.xml$ media/sitemaps/$1/sitemap.xml [L]`` - Generated by a periodic task, not OK for Whitenoise
* ``Alias /media /data/www/developer.mozilla.org/kuma/media`` - Base folder for user uploads and generated files, not appropriate for Whitenoise.
* ``Alias /admin-media /data/www/developer.mozilla.org/kuma/vendor/src/django/django/contrib/admin/media`` - Django 1.3 and earlier used this, not applicable in Django 1.4 and later (we're on 1.8).
* ``Alias /icons/ "/var/www/icons/"`` - Apache icons, not needed by Kuma
* ``Alias /error/ "/var/www/error/"`` - Apache error pages, not needed by Kuma
* ``ScriptAlias /cgi-bin/ "/var/www/cgi-bin/"`` - Apache boilerplate, not needed by Kuma
* ``WSGIScriptAlias /mwsgi /data/www/developer.mozilla.org/kuma/wsgi/kuma.wsgi`` - Apache speak for "/mwsgi is my name for Kuma", not a file served by Django / Whitenoise.

**Comment by metadave** [comment]
any thoughts @jgmize @escattone @pmac?

**Comment by pmac** [comment]
> it will slow down engine startup while Whitenoise calculates hashes for very large, seldom-accessed files.

I didn't realize that whitenoise did this. I know you can have Django calculate hashes and include said hashes in the filenames of files, but it doesn't recalculate ever, it just stores the map of original file to hashed file in a JSON manifest, and all of that happens at build time. I could be mistaken though depending on your configuration.

> RewriteRule ^sitemap.xml$ media/sitemap.xml [L] - Generated by a periodic task. Whitenoise is not appropriate for generated files, may have to be a Django view or other.

Whitenoise is not appropriate for *user* generated files. As long as the file exists at app startup it should work fine. Whitenoise just won't pick up new files added to the document root but should work fine if the file is subsequently updated (I think).

**Comment by jwhitlock** [comment]
@pmac is probably right, whitenoise probably doesn't calculate hashes but leaves this up to Django.  I have little experience with whitenoise.

**Comment by metadave** [comment]
@jwhitlock @escattone I'm unsure if recent PR's have addressed these aliases.

**Comment by jwhitlock** [comment]
Yes, these have been addressed! 😮
