### ISSUE TITLE
decom Ireland cluster

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#336]
- also decom CI/CD pipelines

**Comment by jgmize** [comment]
> 3:31 PM •jgmize removing dublin from www route53 traffic policy
> 3:43 PM •jgmize moved bedrock-prod-eu-west to decom policy in NR
> 3:43 PM •jgmize now that NR is back, things look fine since decom
> 3:43 PM •jgmize moving on to snippets

**Comment by jgmize** [comment]
Removed dublin from snippets-prod traffic policy

**Comment by jgmize** [comment]
Leaving cluster up until tomorrow morning even though no traffic, ready to route traffic back if necessary

**Comment by jgmize** [comment]
we have a cluster autoscaler that should in theory increase the number of worker nodes in the frankfurt cluster to compensate for the additional load anticipated during the EU day. In case that doesn't work, I'm ready to manually increase the minimum number of nodes if necessary.

**Comment by jgmize** [comment]
Moved all eu-west NR apps to decom policy

**Comment by jgmize** [comment]
The ASG & ELBs  in euw aka eu-west aka dublin, ireland have all been deleted after not having any production traffic since yesterday. Despite attempts to proactively silence alerts there were still a few that got triggered after the destruction of dublin. There is more cleanup work in terms of documentation, etc. Will leave this issue open until the remaining documentation issues have been identified and resolved.
