### ISSUE TITLE
MDN interactive examples S3/Cloudfront hosting

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#362]
https://github.com/mdn/interactive-examples/issues/54#issuecomment-315131908

[Note](https://bugzilla.mozilla.org/enter_bug.cgi?product=Infrastructure%20%26%20Operations&component=WebOps%3A%20SSL%20and%20Domain%20Names) for @metadave

**Comment by metadave** [comment]
let's discuss infra here:
cc @jwhitlock @schalkneethling @jgmize

**Comment by metadave** [comment]
Info we'll need:
- domain
  - `moz.works` vs a "more official" sounding domain (mozilla.net?)
- ACM certificate
- IAM role automation (private)
- Cloudfront/S3 automation (public)
-

**Comment by pmac** [comment]
Just a note:

On bedrock we've chosen to assign a CNAME to any `*.moz.works` resources we need for a couple reasons:

1. It's more obvious that the requests to this resource are 1st party and mozilla owned if it's a `*.mozilla.net` address.
2. You'll likely already need `*.mozilla.net` in a CSP if you have or will have one, so that's one less domain to have in the policy.

These are not deal-breakers, but are considerations for which domains to use for such things. I'll also add that we should **not** use `*.mozilla.org` for these to avoid cross-domain cookie security issues.

**Comment by metadave** [comment]
@jwhitlock @jgmize @schalkneethling what domain should we use? (also, see @pmac's comment above)

**Comment by schalkneethling** [comment]
There is a mdn.mozillademos.org that might be an option?

**Comment by metadave** [comment]
There is also [this MDN infra issue](https://github.com/mozmeao/infra/issues/214) related to mdn.mozillademos.org.

**Comment by jwhitlock** [comment]
We can't reuse ``mdn.mozillademos.org``, and shouldn't - it's already doing two things when it should just do one.

One option is a subdomain, like ``interactive-examples.mdn.mozillademos.org``, that is just this project.  WebOps still owns that domain, but they are very fast (less than 15 minutes) to add DNS entries.

Another options is something like ``interactive-examples.mdn.mozilla.net``.  I imagine it has the same issues, that WebOps owns ``mozilla.net``, but it would set a new example.  ``mdn.mozilla.net`` would be a decent source domain for server emails as well.

**Comment by metadave** [comment]
@jgmize (via IRC) suggested to create `interactive-examples.mdn.moz.works` in route53 and then file a bug with webops requesting that they create a CNAME record for `interactive-examples.mdn.mozilla.net`.

**Comment by metadave** [comment]
My vote is that `*.mdn.mozilla.net` may look less suspicious to outside users than `*.mozillademos.org`

**Comment by metadave** [comment]
These resources have been provisioned, but DNS and Jenkins need to be updated.

**Comment by metadave** [comment]
DNS change requested [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1385423)

**Comment by metadave** [comment]
https://interactive-examples.mdn.moz.works/ is working (this is more of a "behind the scenes" domain), I need to update Jenkins to push to the S3 bucket.

**Comment by metadave** [comment]
wip (w/out irc notifications) [here](https://github.com/mdn/interactive-examples/compare/dp_test_deploy?expand=1)

**Comment by metadave** [comment]
https://github.com/mdn/interactive-examples/pull/149

**Comment by metadave** [comment]
https://interactive-examples.mdn.mozilla.net/ is now live.

@schalkneethling @jwhitlock let me know if you have any questions.

**Comment by jwhitlock** [comment]
Thanks @metadave!

This seems to work: https://interactive-examples.mdn.mozilla.net/live-examples/js-examples/array-find.html

And this: https://interactive-examples.mdn.mozilla.net/pages/css/border-style.html

The project could probably use some index documents, so that https://interactive-examples.mdn.mozilla.net isn't just an error, and you can navigate to the examples during development. But that's a different issue...

**Comment by schalkneethling** [comment]
Thought I asked this question but, seems I did not ;p Now that we have CloudFront configured with the interactive examples, how do we cache bust? Does it automatically do that whenever a merge to master happens? i.e. this would trigger a push from Tavis to the prod branch @metadave @jwhitlock

**Comment by metadave** [comment]
@schalkneethling Cloudfront [ttl](https://www.terraform.io/docs/providers/aws/r/cloudfront_distribution.html#default_ttl) is currently set to [60 seconds](https://github.com/mozmeao/infra/blob/master/apps/mdn/interactive-examples/tf/mdninteractive.tf#L116), so a push will show up after this short delay (plus whatever "magic" Cloudfront does behind the scenes). We can also look into [cache invalidation](http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/Invalidation.html) at some point in the future.

**Comment by schalkneethling** [comment]
@metadave Thx. That is totally reasonable. I doubt that it will ever cause an issue.
