### ISSUE TITLE
hosted Elasticsearch kuma analysis

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#383]
parent: https://github.com/mozmeao/infra/issues/193

**Comment by metadave** [comment]
connecting to hosted Elasticsearch requires a few additional parameters, let's see how this impacts the code in Kuma:

```
es = Elasticsearch(
    ['hosted_es_url'],
    http_auth=('some_username', 'some_password'),
    port=9266,
    use_ssl=True
)
```

**Comment by metadave** [comment]
example: https://gist.github.com/metadave/7dec910e623b8186680b09bec7b0d2ba

**Comment by jwhitlock** [comment]
We setup the ElasticSearch connection in [kuma/wiki/apps.py](https://github.com/mozilla/kuma/blob/4b48a53d0da7464d6e11a9b930d6e245fdca8d21/kuma/wiki/apps.py#L60-L69).  It's not much different from your example. It could be adjusted to add these parameters from Django settings pulled from the environment.  My preference would be to use something like [dj-database-url](https://github.com/kennethreitz/dj-database-url)'s database URLs, but it's not a strong preference - we can probably use ``ES_USERNAME``, ``ES_PASSWORD``, etc. for the same effect.

**Comment by metadave** [comment]
thanks @jwhitlock, it seems like it will be a relatively minor tweak. @escattone is going to take a look at this next week.

**Comment by metadave** [comment]
It might be worthwhile to ensure connecting with or without a password works.

**Comment by escattone** [comment]
@metadave @jwhitlock From my reading of the [docs for the low-level Elasticsearch client](https://elasticsearch-py.readthedocs.io/en/master/api.html#elasticsearch.Elasticsearch) that underlies `elasticsearch-dsl`, we will not have to change the way Kuma configures the Elasticsearch connection settings in [kuma/wiki/apps.py](https://github.com/mozilla/kuma/blob/4b48a53d0da7464d6e11a9b930d6e245fdca8d21/kuma/wiki/apps.py#L60-L69) since we can use the following form when setting `ES_URLS` (or `ELASTICSEARCH_URL` at the `Makefile` level)
```
https://<username>:<password>@<host>:<port>
```
It seems to work when I try it using the trial service that @metadave set-up, in the sense that it seems to successfully communicate. However, when I try to add or populate an index, I get:
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/app/kuma/core/decorators.py", line 152, in wrapped
    return func(*args, **kwargs)
  File "/app/kuma/search/tasks.py", line 44, in prepare_index
    es.indices.put_settings(temporary_settings, index=index.prefixed_name)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/indices.py", line 620, in put_settings
    '_settings'), params=params, body=body)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/transport.py", line 307, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_urllib3.py", line 93, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/base.py", line 105, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
NotFoundError: TransportError(404, u'index_not_found_exception')
```
So I need to look into that.

**Comment by escattone** [comment]
@metadave @jwhitlock It turned out to be a version mismatch. The trial service that @metadave created was at 5.x, but Kuma needs 2.4.x. It was failing at https://github.com/mozilla/kuma/blob/5dbf2ca890088067447fe66d7c200faf4bd466cd/kuma/search/managers.py#L65 (silently, because the `RequestError` is ignored). When I ran the command, captured the exception, and squeezed it until it talked, it told me this (among other similar messages for different fields):
```
Failed to parse mapping [wiki_document]: The [string] type is removed in 5.0 and automatic upgrade failed because parameters [term_vector] are not supported for automatic upgrades. You should now use either a [text] or [keyword] field instead for field [summary]
```
I've created a new trial service at version 2.4.6 and will give that a try.

**Comment by escattone** [comment]
The `www.elastic.co` trial service running version 2.4.6 seems to work great! 🎉

**Comment by jwhitlock** [comment]
Brain-dump on ElasticSearch:

Elastic.co has an interesting policy of libraries being forward compatible. So, if you are running ElasticSearch 5.0, they claim you can use 1.x, 2.x, or 5.x libraries.: 

https://github.com/elastic/elasticsearch-py#compatibility

This worked to our advantage during the 1.x to 2.x server update, since we could stay on the 1.x libraries and not coordinate a production push with the server update. So, it's a good policy. It seems that maybe the 1.x library doesn't work with an ES 5.x server, though, which isn't clear from the docs.

I'd like to update to 2.x client libraries, but that would (hopefully) break some tests. We currently have live tests that make actual calls to an ES server, which is bad practice for non-integration tests.  I'd like to update these tests to call a mocked service before the 2.x library update.

None of this is a blocker for the AWS move, as far as I can tell. But, I have a plan in my back pocket if it does end up being a blocker.

**Comment by escattone** [comment]
Here's an idea of the monthly cost for a production-grade cluster that I think would suit our needs:

<img width="311" alt="image" src="https://user-images.githubusercontent.com/3743693/29194423-604b27e2-7dde-11e7-8c0b-c3d21ca820a1.png">

These are the exact characteristics of the trial service, except for the high-availability.

**Comment by escattone** [comment]
There are also some interesting tools for migrating from 2.x to 5.x, which might be helpful for us:

<img width="915" alt="image" src="https://user-images.githubusercontent.com/3743693/29195351-e40b3b72-7de2-11e7-8d2a-925350d05be6.png">

**Comment by escattone** [comment]
Thanks for the info @jwhitlock ! It seems that the 5.x cluster didn't like the field types used for the document mappings, so I suppose that's not considered a client issue.

**Comment by escattone** [comment]
When we upgrade to 5.x, it seems that one of the things we need to do is to change all `field.String` to either `field.Text` or `field.Keyword` [here](https://github.com/mozilla/kuma/blob/5dbf2ca890088067447fe66d7c200faf4bd466cd/kuma/wiki/search.py#L28-L52).

**Comment by escattone** [comment]
I think we can close this? I'd call this eval successful!

**Comment by metadave** [comment]
thanks for the research @escattone @jwhitlock!

**Comment by metadave** [comment]
@escattone what's your recommendation for dev/stage? Do we need a smaller elastic.co cluster for stage, and [K8s hosted ES](https://github.com/mozilla/kuma/tree/master/k8s) for dev?

**Comment by metadave** [comment]
note: for disk space, we use ~4GB for Kuma, and Sumo uses ~6GB

**Comment by escattone** [comment]
Thanks @metadave! I was thinking that in addition to the elastic.co instances for stage and prod, we'd also create a single dev instance (not to be used for personal development by anyone, but as a shared instance for development by staff without affecting staging). Are we going to allow personal dev environments? I was thinking that we probably shouldn't as it would be too costly (If we did, we'd probably need a separate K8s cluster to handle those?).

Here's what I'd recommend:
- production instance
        4GB RAM, 96GB SSD storage, 2 data centers (redundant)
        cost: $229/month (annual contract provides %15 reduction to $195/month)
- stage instance
        1GB RAM, 24GB SSD storage, 1 data center (no redundancy)
        cost: $45/month (annual contract provides %15 reduction to $38/month)
- dev instance
        1GB RAM, 24GB SSD storage, 1 data center (no redundancy)
        cost: $45/month (annual contract provides %15 reduction to $38/month)

**Comment by metadave** [comment]
@escattone after we go live, I'd say dev instances should just use [this](https://github.com/mozilla/kuma/tree/master/k8s) method of deploying ES.

**Comment by escattone** [comment]
@metadave For personal dev instances, I agree with you, although it seems to me it might be useful to maintain a dev instance of Elastic Cloud with which we (SRE's and MDN staff backend developers) could experiment (e.g., explore migration from 2.x to 5.x) without affecting the stage instance.

**Comment by jwhitlock** [comment]
@escattone I think we can provision a new ElasticCloud instance for development as needed at the hourly rate, rather than maintain one for testing that we mostly don't use.

**Comment by metadave** [comment]
lets use the specs from [this](https://github.com/mozmeao/infra/issues/383#issuecomment-322566268) comment when provisioning new instances.
