### ISSUE TITLE
investigate refactor of custom collation using standard MySQL features

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#399]
- let's find out what's involved in removing custom collation from MySQL so we can move to RDS instead of hosting MySQL ourselves.

**Comment by jwhitlock** [comment]
I think we can do this in the next two weeks, but I'll need to coordinate w/ writers and do a little more research.

I've loaded the current anonymized database locally, and tried to convert the collation:

    SET FOREIGN_KEY_CHECKS=0;
    ALTER TABLE taggit_tag MODIFY name varchar(100) CHARACTER SET utf8 COLLATE utf8_unicode_ci;
    ALTER TABLE wiki_documenttag MODIFY name VARCHAR(100) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL;
    ALTER TABLE wiki_localizationtag MODIFY name VARCHAR(100) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL;
    ALTER TABLE wiki_reviewtag MODIFY name VARCHAR(100) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL;
    SET FOREIGN_KEY_CHECKS=0;

This works for ``wiki_localizationtag`` and ``wiki_reviewtag``, but does not for ``taggit_tag`` (mostly profile interests and expertise) and ``wiki_documenttag`` (the document tags we know and love), because of duplicate tags in the ``utf8_unicode_ci`` collation.

Here's the SQL to find the duplicate tags:

    SELECT name, COUNT(*) c FROM taggit_tag GROUP BY name COLLATE utf8_unicode_ci HAVING c > 1;
    SELECT name, COUNT(*) c FROM wiki_documenttag GROUP BY name COLLATE utf8_unicode_ci HAVING c > 1;

For ``taggit_tag``:

```
+--------------------------------------------+---+
| name                                       | c |
+--------------------------------------------+---+
| profile:interest:arr?ter de fumer          | 2 |
| profile:interest:programacion              | 2 |
| profile:interest:que es la andropausia     | 2 |
| profile:interest:sintomas de la menopausia | 2 |
+--------------------------------------------+---+
```

For ``wiki_documenttag``:

```
+---------------------------------+---+
| name                            | c |
+---------------------------------+---+
| actualizacion                   | 2 |
| Audio                           | 2 |
| Basic                           | 2 |
| Basico                          | 2 |
| busquedas                       | 2 |
| Controleur                      | 2 |
| CSS Reference                   | 2 |
| CSS Referencia                  | 2 |
| Debutant                        | 2 |
... a lot more omitted ...
+---------------------------------+---+
```

I'll need to do some more research to determine how tags are used, what the duplicate tags are, and what the repercussions would be to de-dupe the tags.

This is already getting long for a GitHub comment, so I'm starting a [Google Doc](https://docs.google.com/a/mozilla.com/document/d/1xGeFQuRZa_aJ_obpgKHgGXT-8NQg61lFyD98eKedyz0/edit?usp=sharing).  I'll probably need a spreadsheet too.  Then I'll talk to the content team about the repercussions, and start the discussion of first-class localized tags for post-AWS

I want to tackle the [conversion to full unicode](https://mathiasbynens.be/notes/mysql-utf8mb4) as well, but I don't think that's an AWS blocker, so I'll wait.

**Comment by jwhitlock** [comment]
OK, I think I've got my recommendation complete:

* [MySQL Collation, AWS, and Tags](https://docs.google.com/document/d/1xGeFQuRZa_aJ_obpgKHgGXT-8NQg61lFyD98eKedyz0/edit?usp=sharing)
* [Tags Spreadsheet](https://docs.google.com/spreadsheets/d/1QjuT5vj1-yLcVa-XNt9JFHNKR3lKryOd162PkY5SLD4/edit?usp=sharing)
* [bug 1391084](https://bugzilla.mozilla.org/show_bug.cgi?id=1391084)

These are public docs, but the gist is:

* There's a little over 200 tags that are duplicates in the ``utf8_general_ci`` collation that are unique in the ``utf8_distinct_ci`` collation
* Some break the "translated tags" feature. For example, both "Reference" and "Référence" are not allowed, and many French pages will start getting the former. However, this is a hack for a first-class translated tags feature, which we can start building.
* The conversion can be done automatically in a ugly, MySQL-only database migration, by adding `` (2)`` or similar strings to make tags unique.

@metadave does this issue just cover the investigation, or the implementation as well?

**Comment by metadave** [comment]
@jwhitlock I've been creating separate issues for analysis and implementation. If you think the implementation issue will be mostly empty, then feel free to use this.

**Comment by jwhitlock** [comment]
There weren't any objections so far from the content team, so I'm proceeding.  I do need to analyze tag usage in the KumaScript macros, to check that my proposed changes won't break existing functionality.

Based on past data migrations, I think it will take 1-3 days to implement, so tracking that in #435.
