### ISSUE TITLE
Implement database backup and restore process for go-live

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#401]
This should be split into 2 sections:
- going live in maintenance mode
- going line in production

**Comment by jwhitlock** [comment]
I'm assuming an unencrypted MySQL dump in an S3 bucket is needed to populate an RDS instance, but I haven't researched it.

Here's what I'm doing today:

1. Use a read-only connection to a MySQL replica server over the VPN to create a database dump
2. ``gzip`` the database dump.
3. Use the [clone_db.py](https://github.com/mozilla/kuma/blob/master/scripts/clone_db.py) script to load the prod database and create an anonymized database
4. Upload to the read-limited S3 bucket using ``s3cmd``

This takes 4-8 hours. I usually do it overnight, because it makes my laptop useless for interactive work. 

We could ask the data team / person to create the anon DB inside the SCL3 datacenter, optionally encrypt it, and upload it to S3, which would probably save time over transferring data to my laptop.  The S3 upload took about 150 minutes last time I tried it, but I was doing other things with my laptop, such as video meetings.

**Comment by jgmize** [comment]
@jwhitlock why not use the dedicated mysql instance we already have in SCL3 for this instead of your laptop? I don't see any reason why we can't install aws CLI and store the s3 credentials on that VM, and copy the gzipped mysql dumps directly from it to a private s3 bucket. A basic outline of this would look like:

1. pause mysql replication
2. mysqldump to gzipped & timestamped $PROD_BACKUP file
4. aws s3 cp $PROD_BACKUP s3:///$PROD_DB_BACKUPS_BUCKET_NAME
5. anonymize DB
6. mysqldump to gzipped $ANON_BACKUP file
7. aws s3 cp $ANON_BACKUP s3://$ANON_DB_BACKUPS_BUCKET_NAME
8. restore from $PROD_BACKUP
9. resume mysql replication

This should be fairly straightforward to script and run as a cron job on that VM.

**Comment by metadave** [comment]
I have a prod backup + gzip + encrypt + s3 push down to about 15 minutes, details incoming soonish. Do we need an anonymized database for going live in maintenance mode?

See: https://bugzilla.mozilla.org/show_bug.cgi?id=1397850

**Comment by metadave** [comment]
This works, when we go live officially, we'll need to disable replication as mentioned above: https://gist.github.com/metadave/9e17a11875adad4ffed34e1d1ddfe7bf

**Comment by metadave** [comment]
calling this finished for now, we can open a new issue and link to this one with any further work.
