### ISSUE TITLE
maintenance mode release plan

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#409]
I'm starting a list of things to take care of during the maintenance deploy:

- ensure cluster is appropriately scaled
  - ensure autoscaler max is set higher than the default (the default for the portland cluster will be very low, as it was created with 2 nodes initially).
- ensure static files from `/data` are synced over to the appropriate locations.
- disable Kuma web services
  - what's the preferred method here? via DNS?
  - do we redirect traffic to a maintenance page? 
- wait for redis/memcache queues to drain
  - what tool can we use to monitor this?
- ~backup production MySQL database~ -> we're using the anonymized db
- ~restore production database in AWS deployment~
- ensure [mdn.mozillademos.org DNS](https://github.com/mozmeao/infra/issues/214) is correct.
- change developer.mozilla.org DNS to point at AWS deployment

DNS change info: https://github.com/mozmeao/infra/issues/396

**Comment by jwhitlock** [comment]
The database needs to be in place at the start of maintenance mode.  We'll need to backup the MySQL database, anonymize or encrypt it, get it to AWS, and load it.  We'll then do the DNS switch to send traffic to AWS instead of SCL3.

I think SCL3 will just not have any traffic in MM, with all the traffic going to AWS via a DNS switch.  I was thinking it would work the same way in AWS, with the "live cluster" not getting traffic, and the "mm cluster" getting the traffic, via DNS.  This allows us to do the maintenance on the live cluster, run tests using private DNS names, etc., before switching the DNS back.

Maintenance mode, in general, will have yesterday's data. Once we're in AWS, we can tighten this up with last-hour's snapshot for planned maintenance, but 24-hour-old data is better that our current "we're working on it" splash page.

It is not OK to ever have a de-anonymized production database in a publicly accessible location. We currently restrict the anonymized database to select staff and NDA-ed contributors.  I'd like to ensure we do the same with the AWS transition, by encrypting the database dump in flight and at rest, and ensuring narrow permissions on S3 buckets holding it.

**Comment by metadave** [comment]
See https://github.com/mozmeao/infra/issues/401 for DB backup scripting.

**Comment by jwhitlock** [comment]
I think this belongs in the A3 milestone, when we start sending production traffic to AWS in maintenance mode.

**Comment by jwhitlock** [comment]
Since this was opened, we decided to do a mixed maintenance mode test:

* SCL3 will run in maintenance mode
* AWS production will run in maintenance mode on a recent production backup
* Use [Route53 weighted traffic policy](http://docs.aws.amazon.com/Route53/latest/DeveloperGuide/routing-policy.html#routing-policy-weighted) to send developer.mozilla.org traffic to both data centers, starting at 5% and climbing.
* All mdn.mozillademos.org and developer.cdn.mozilla.net traffic will continue going to SCL3 for this test ( ❓@metadave ❓ ) 

I think the new task list is:

* Add a soapbox to developer.mozilla.org scheduling the test, 8 to 24 hours in advance
* Prepare AWS production for maintenance mode
  - load a recent production backup (less than a week old)
  - ensure autoscaler max is set higher than the default (the default for the portland cluster will be very low, as it was created with 2 nodes initially).
  - run any tasks that require DB access (sitemap generation, etc.)
  - set to maintenance mode, read-only DB
  - set to serve developer.mozilla.org, confirm w/ local ``/etc/hosts`` override
* Set SCL3 production into maintenance mode
  - Details to be worked out in [milestone A2](https://github.com/mozmeao/infra/milestone/14)
  - Push branch with maintenance mode set as default, read-only DB
  - Disable ``celerybeat`` and ``celerycam`` on ``developer-celery1``
  - Watch celery logs for evidence that queue is drained
  - (Optional) Get WebOps to confirm queues are drained, or are MM-safe tasks
* Finalize AWS deployment 
  - Ensure static files from `/data` are synced over to the appropriate locations.
  - For "go-live" day, this is where we'll create the final prod DB backup
* Send some traffic to AWS
  - Change developer.mozilla.org DNS to send 5% (or more) traffic to AWS deployment
  - Monitor New Relic, Sentry, AWS tools
  - Revert DNS traffic to SCL3
* Finish the test 
  - Push "regular" SCL3 mode (should restart ``celerybeat`` and ``celerycam``)
  - Record performance results, bugs to fix, etc. etc.

**Comment by metadave** [comment]
> All mdn.mozillademos.org and developer.cdn.mozilla.net traffic will continue going to SCL3 for this test ( ❓@metadave ❓ )

- The new CDN is setup and can be used if we like (for the AWS deployed resources only), it would just be a simple Kuma setting tweak. Leaving it as-is will work too, and there's less to change for this test if that's what we choose.
- mdn.mozillademos.org is a CNAME for mdn-demos.moz.works, so I can easily change it's value in Route 53 to point at our MDN prod K8s ELB. We can also leave this one as is for this test if you like.

**Comment by jwhitlock** [comment]
Here's my proposal:
* For the Maintenance Mode traffic tests, point the CDN and Demo load balancers at SCL3 alone, with no traffic going to AWS.
* For the AWS Staging Read/Write manual tests, point the CDN and Demo load balancers at AWS alone, with no traffic going to SCL3
* For the go-live date, do a 100% load balancer switch from SCL3 to AWS for the CDN, Demo, and Web servers.

Long version:

It shouldn't matter which CDN is used, since most requests should go to CloudFront (CloudFlare?). As long as SCL3 and AWS refer to the same assets, then it shouldn't matter what Kuma web server handles CloudFront cache misses. With PR #457, we're using the same asset tools in both environments, so they *should* be referring to the same assets. The problem is if we're wrong.

We include a hash of the asset contents in the name with a very long cache expiration, so if there is a difference (asset pipeline, different Kuma commits) the filename will be different, and CloudFront will request a new asset.  If we got something wrong, AWS will claim a different asset hash than  SCL3. CloudFront will flip a coin, and probably ask SCL3 for the asset. SCL3 will return a 404, and CloudFront will capture it. This is the good result - we can see the 404 in manual testing, and try to figure it out. The bad result is that CloudFront accidentally gets the asset from SCL3 as well, and we miss the error.  Sending all CDN traffic to SCL3 servers means that we have 100% chance of seeing these asset differences as 404s.

The demo server is a similar story, but I think the effects are less. The manual testing of SCL3 staging shows that there are lots of errors when the database is inconsistent with the attachments file server. I have a lot of confidence in the file syncing from SCL3 to AWS (thanks @metadave!), so I think there are a lot less risks to sending some of the demo traffic to AWS. I'm also not sure it is an important part of the traffic test. I'd support 100% to SCL3 or a percent to AWS, and slightly favor the lazy option of not changing it.

I think we'll get coverage of CDN and Demo issues when we switch the AWS Staging server to read/write mode, and we'll be as confident as we can be for the go-live date.

**Comment by metadave** [comment]
+1 to your writeup above @jwhitlock 

Adding to the list:
notify #moc #webops before and after the DNS change.

**Comment by jwhitlock** [comment]
We've successfully tested maintenance mode with 100% of traffic to Portland k8s using this process.
