### ISSUE TITLE
setup stage Elasticsearch instance

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#429]
Once we have billing established, let's create stage/prod ES instances.

See: https://github.com/mozmeao/infra/issues/383

**Comment by metadave** [comment]
stage instance has been created and credentials are in mdn-k8s-private.

**Comment by metadave** [comment]
@escattone when you have a moment, can you test Kuma connectivity with the new stage instance?

**Comment by jwhitlock** [comment]
Can we call this task complete, since search is working at [mdn-mm.moz.works](https://mdn-mm.moz.works/en-US/search?q=HTML&topic=apps&topic=html&topic=css&topic=js&topic=api&topic=canvas&topic=svg&topic=webgl&topic=mobile&topic=webdev&topic=http&topic=webext)?

Also, connectivity may be affected by https://github.com/mozilla/kuma/pull/4425

**Comment by metadave** [comment]
Yes, stage has been provisioned. @escattone should we open an issue to ensure that Elasticsearch connectivity isn't impacted by https://github.com/mozilla/kuma/pull/4425?

**Comment by jwhitlock** [comment]
Opened https://github.com/mozmeao/infra/issues/481 to install and test urllib3 1.22.
