### ISSUE TITLE
discuss target dates for MDN milestones

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#493]
We need to establish a few ***soft*** target dates for the following milestones:

- MDN AWS A1: MM Manual Testing
  - September 18th
- MDN AWS A2: MM SCL3 Test (non-AWS)
  - September 19th
- MDN AWS A3: MM Production Traffic (w/ weighted traffic policy)
  - September 21th
- MDN AWS B1: Stage Manual Testing
  - tbd

**Dates listed above are just suggestions and can be changed!** Let's use this issue for discussion unless you'd like to move to a different forum.

**Comment by jwhitlock** [comment]
I'd like to add a day, because I get about an hour of working time on Mondays.

* MDN AWS A1: MM Manual Testing - Tuesday, September 19th
* MDN AWS A2: MM SCL3 Test (non-AWS) - Wednesday, September 20th
* MDN AWS A3: MM Prod Traffic - Thursday, Sept 21st
* MDN AWS B1: Stage Manual Testing - Thursday, Sept 28th

This assumes passing tests, but I think we can schedule maintenance on developer.mozilla.org 12-24 hours in advance. Maintenance mode isn't active on https://mdn-mm.moz.works yet, but I bet we can do it on Monday.
