### ISSUE TITLE
Stalled asset loading leading to high load times

### ISSUE THREAD

**Issue by atopal** [mozmeao/infra#648]
We're currently looking into ways to mitigate high page load times for the new interactive editor feature on MDN. One thing we have noticed is that part way through the page load the delta between asset request and asset delivery starts to balloon. Here's an example, but the the effect is consistent between tests: 
https://www.webpagetest.org/video/compare.php?tests=171113_89_babbc0804f6d428115194be23bacc15e-r:1-c:0

On line 20 you can see the request start at 1.7s, but the first byte arrives 1s later, same for requests on line 27 and 28, while the same domain is delivering first byte within .2 seconds earlier in the time line (line 10-13). We're not sure how to interpret the results, but if these are real, we're losing 2s during page load just waiting for assets. Filing this issue, so we can discuss whether this is worth looking into further.

**Comment by metadave** [comment]
The `interactive-examples.mdn.mozilla.net` domain is served by S3 and Cloudfront, which allows us a quick/cheap/easy way of serving static content. However, there have been [reports of performance degradation](https://github.com/mdn/viewsourceconf/issues/198) on the viewsourceconf site, which uses the same style of hosting. Additionally, we should ensure that the Django code serving interactive examples should be including appropriate caching headers to take advantage of CDN caching.

See also https://github.com/mozmeao/infra/issues/391

**Comment by metadave** [comment]
ah, the MDN devs are working on tweaks: https://github.com/mdn/interactive-examples/issues/311

**Comment by jwhitlock** [comment]
It may be a recent addition, but you can add arbitrary headers to S3-hosted content:

http://docs.aws.amazon.com/AmazonS3/latest/user-guide/add-object-metadata.html

It should be possible to add CSP, expiration dates / max age, etc. etc. There's options to ``aws s3 sync``, as well as ``aws s3api copy-object`` to update metadata on existing files.

**Comment by jwhitlock** [comment]
After assembling a bit of data I realized you were talking about the interactive-examples CDN, not the Mozilla CDN. A recent PR, https://github.com/mdn/interactive-examples/pull/329, removes ``require.js`` loading and instead loads the scripts directly. This should have an impact, since it removes some JS that needs to load and run to request further assets, and instead requests them directly. The webpagetest tool should be re-run.

Here's some timing data for the MDN CDN:

| Line | Name | Time to First Byte | Content Download | Bytes In | H2 Stream |  H2 Depends On |
| --- | --- | --- | --- | --- | --- | --- |
| 2 | font-check.js | 137 ms | 1 ms | 0.5 KB | 11 | 
| 3 | wiki-skinny.css | 74 ms | 1 ms | 11.0 KB | 5 | 
| 4 | locale-en-US.css | 65 ms | 0 ms | 0.7 KB | 3 |
| 5 | javascript.js | 135 ms | 1 ms | 0.8 KB | 9 |
| 6 | main.js | 118 ms | 16 ms | 44.9 KB | 7 | 
| 7 | mdn-skinny.js | 63 ms | 1 ms | 14.5 KB | 1 | 0 |
| 8 | wiki-skinny.js | 73 ms | 0 ms | 5.7 KB | 13 | 11 |
| 9 | newsletter.js | 74 ms | 0 ms | 1.3 KB | 15 | 13 |
| 14 | web-docs-sprite.svg | 58 ms | 4 ms | 3.3 KB | 17 | 0 | 
| 16 | ZillaSlab-Bold.woff2 | 148 ms | 286 ms | 66.7 KB | 3 |
| 17 | fontawesome-webfont.woff | 66 ms | 74 ms | 81.9 KB | 1 | 0 |
| 18 | ZillaSlab-Regular.woff2 | 537 ms | 518 ms | 67.0 KB | 5 |
| 21 | OpenSans-Regular.woff2 | 1483 ms | 530 ms | 46.1 KB | 7 | 5 |
| 22 | OpenSans-Semibold.woff2 | 2195 ms | 1 ms | 46.6 KB | 9 | 7 |
| 23 | OpenSans-Italic.woff2 | 892 ms | 554 ms | 55.5 KB | 11 | 9 |
| 24 | ZillaSlab-Italic.woff2 | 2013 ms | 2 ms | 61.6 KB | 13 | 11 |
| 25 | syntax-prism.js | 2186 ms | 1 ms | 5.6 KB | 19 | 0 |
| 29 | favicon32-local.png | 58 ms | 0 ms | 0.8 KB | 21 | 0 |

These were requested with HTTP/2, which I'm not very familiar with. It does smell like the assets are all requested at the same time, but delivered sequentially over the HTTP/2 channel. You can see in the diagram that lines 16, 17, and 18 are requested at the same time, and they are fully delivered one after the other (17 then 16 then 18).  There's a similar pattern for 23 then 21 then 24 then 22.  HTTP/2 Stream shows a value such as "7, weight 256, depends on 5" for line 21, OpenSans-Regular-webfont.3f642fa3ea74.woff2, but this doesn't appear to correspond to the returned order of assets.

I'm suspect that a long time to first byte is an aspect of loading many assets at once over HTTP/2, and should not be a concern.

**Comment by atopal** [comment]
I think you're right about cdn.mdn.mozilla.net, and you can see that quite nicely with the font files, requested at the same time and delivered sequentially; as soon as the download of one file is done the next is downloaded. I'm not sure whether that explains the 1+1s time to first byte for interactive-examples.mdn.mozilla.net though. I guess we should look at that after the next push to production that unbreaks that experiment. 

Something unrelated that caught my eye, and maybe something to look into later: since prism.js is requested after the large font files and downloads are sequential, prism.js might be render blocking for quite some time.

**Comment by stephaniehobson** [comment]
![screen shot 2017-11-22 at 11 12 31](https://user-images.githubusercontent.com/854701/33146200-242525ec-cf78-11e7-895a-2847ab239b47.png)

This is not how a CDN is supposed to work. Has there been any progress looking into this?

**Comment by stephaniehobson** [comment]
Or can we please have a timeline so that we know not to ask for updates until after a certain date?

**Comment by jgmize** [comment]
@stephaniehobson and I just discussed next actions on this; she's going to do another round of tests against the scl3 and aws staging envs, and then we're going to try disabling http2 by adding [http_version = 1.1](https://www.terraform.io/docs/providers/aws/r/cloudfront_distribution.html#http_version) to the [staging CDN terraform](https://github.com/mozmeao/infra/blob/master/apps/mdn/mdn-aws/infra/mdn-cdn/mdn_cdn.tf#L15) and do another round of tests.

**Comment by jgmize** [comment]
@stephaniehobson please ping me in IRC or slack whenever you're ready for me to apply the terraform change referenced above.

**Comment by stephaniehobson** [comment]
Spent most of yesterday working on this but I'm not ready for the switch yet. 

Somethings I have found in my testing so far:
- I can't reliably reproduce the issue using anything other than webpagetest.org, though I have seen it unreliably in Firefox.
- webpagetest.org reproduces it reliably on prod but not on staging.

**Comment by stephaniehobson** [comment]
Update after further testing:
- The sequential font loading does not correlate with slower load times.
- There is big variance in load times between tests.
- webpagetest.org might be part of the problem. I'm not able to replicate the problem with any other testing service (dareboost, pingdom) and it's only happened once or twice locally. We also think it is using an older version of Firefox but can't verify that.

Since it does not correlate with higher load times and we are not sure how best to solve this particular oddity, or even measure if we've made an improvement, I'm going to move on to working on something else.

**Comment by jwhitlock** [comment]
We've made a few changes from December 2017. developer.mozilla.org is now served from CloudFront, and assets are now served from the primary domain. This has had a positive impact on site performance, see the [April 2018 Changelog](https://hacks.mozilla.org/2018/05/cdn-bcd-and-svg-mdn-changelog-for-april-2018/) for details.

@tkadlec is auditing performance issues on MDN Web Docs, and may have recommendations about assets. Closing this issue as stale.
