### ISSUE TITLE
Increase RDS storage space of mariadb us-west

### ISSUE THREAD

**Issue by glogiotatidis** [mozmeao/infra#654]
The SUMO database currently weights 93Gb. So we need at least 200Gb of free space in our MariaDB rds instances and replicants to be able to have two copies of it.

Command used to calculate size:
```
SELECT table_schema "Data Base Name",
    sum( data_length + index_length ) / 1024 / 1024 "Data Base Size in MB",
    sum( data_free )/ 1024 / 1024 "Free Space in MB"
FROM information_schema.TABLES
GROUP BY table_schema ; 
```
```
+---------------------+----------------------+------------------+
| Data Base Name      | Data Base Size in MB | Free Space in MB |
+---------------------+----------------------+------------------+
| information_schema  |           0.00976563 |       0.00000000 |
| support_mozilla_com |       93205.15625000 |    1751.00000000 |
+---------------------+----------------------+------------------+
```

**Comment by metadave** [comment]
According to the "Settings for MariaDB DB Instances" section of [this](http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_ModifyInstance.MariaDB.html) document, changing the allocated storage space won't cause any downtime, but "Performance may be degraded during the change. "

**Comment by metadave** [comment]
@jgmize any ideas on how to proceed?

**Comment by jgmize** [comment]
@metadave and I just discussed our options, summarizing here:

Because of global replication, we can't just increase the size in us-west: we'd need to increase the storage in all the regions. There would also be a performance degradation for all the sites that use mariaDB (snippets, basket, & careers) for an unknown time frame. The quickest, safest, and most cost effective option for this quarter is to spin up a new t2.small RDS instance appropriately sized for sumo dev, and then we can plan on resizing as necessary as we may need to increase to a t2.medium or larger for dev. For prod we would plan on using a larger instance.

@bensternthal the monthly cost on a t2.small RDS instance is ~$49/mo, and if we need a t2.medium it'll be ~$98/mo.

**Comment by jgmize** [comment]
closing old issue; we ended up giving SUMO dedicated RDS instances.
