### ISSUE TITLE
Eliminate DB dependency from liveness & readiness endpoints in Kuma

### ISSUE THREAD

**Issue by jgmize** [mozmeao/infra#660]
When MySQL is slow to respond, these endpoints are slow to respond, which causes a cascading failure situation.

Original implementation in https://github.com/mozilla/kuma/pull/4240

**Comment by escattone** [comment]
Thanks for bringing this up @jgmize. In my original middleware-based implementation, the liveness endpoint did not depend on MySQL, just the readiness endpoint. In the current view-based implementation, since requests go through the entire middleware stack (which hits MySQL), now both endpoints dependent on MySQL.

I think we should at least move the liveness endpoint back to a middleware implementation situated at the very beginning of the stack, so it no longer depends on MySQL. It seems to me that the readiness endpoint should remain dependent on MySQL, since Kuma isn't ready without it, but maybe we need to increase the K8s timeout for readiness probes?

**Comment by jgmize** [comment]
There was another downtime event this morning where a scraper was hitting a bunch of URLs with poorly optimized SQL queries, resulting in increased DB latency and therefore healcheck and liveness probe failures. I temporarily removed the probes specified in this template https://github.com/mozmeao/infra/blob/master/apps/mdn/mdn-aws/k8s/kuma.deploy.yaml.j2#L15-L32 via `kubectl edit`.

**Comment by jgmize** [comment]
> It seems to me that the readiness endpoint should remain dependent on MySQL, since Kuma isn't ready without it, but maybe we need to increase the K8s timeout for readiness probes?

No, please remove the DB dependency from both probes. Leaving the dependency in the readiness probes leaves us open to another cascading failure situation.

**Comment by metadave** [comment]
Whats the best way to monitor MySQL perf if the probes are removed?

**Comment by jwhitlock** [comment]
If web pods are unable to connect to the database, we'll see a significant increase in 500 errors.  New Relic will alert us at 5% or greater. If the database connection fails, the homepage may also fail, and we'll get a downtime alert.

Here's the average response time during the event in New Relic. This gives a visual indication that something is up:

<img width="635" alt="nr response time" src="https://user-images.githubusercontent.com/286017/33436619-325df3c6-d5ab-11e7-9b70-b9f42b74575f.png">

Here's Database connections. It seems like a weaker signal, but does show a spike during the incident. I suspect that if Kubernetes wasn't killing web pods, a sustained high # of DB connections would be a good signal, but it would be proportionate to the total number of pods, so the math would be hard for alerting:

<img width="928" alt="aws db connections" src="https://user-images.githubusercontent.com/286017/33436778-97c34d74-d5ab-11e7-943b-fcd59426fcd9.png">

Here's Read IOPS from AWS. This does not appear to be a strong indication of database overload:

<img width="910" alt="aws read iops" src="https://user-images.githubusercontent.com/286017/33436718-6c5ed39c-d5ab-11e7-8f49-c0d3c0f52ade.png">

CPU % is also a weak signal under current conditions:

<img width="923" alt="aws cpu" src="https://user-images.githubusercontent.com/286017/33436910-facbe8c2-d5ab-11e7-989a-91fcfa1789cd.png">

I'd like to:

1) Remove the query from the readiness probe, making it identical to the liveness probe. I don't want to move it into a middleware at this time, or take heroic efforts to remove DB access from middleware.

https://github.com/mozilla/kuma/blob/42d7186c4ebdbdbbbe5f4e5c7826e7b498b2ad93/kuma/health/views.py#L28-L36

2) Rely on NR alerting for the "no database" situation, and re-evaluate when that problem appears.

3) Review AWS metrics during the next scraping incident, and see if there are metric levels that would give a good alert with minimal false positives.

**Comment by escattone** [comment]
Thanks for the detailed graphs and analysis @jwhitlock. It is my understanding that K8s only uses the liveness probe in its determination of whether or not to terminate and restart a pod, and the readiness probe for whether or not to route traffic to the pod, but maybe I'm off.

I did a quick review of the Kuma middleware, and I think the `kuma.wiki.middleware.DocumentZoneMiddleware` is the only remaining layer that might hit the DB during a request (but only if the cache is empty or invalidated, so not on every request).

**Comment by jwhitlock** [comment]
I think I'm confusing readiness and liveness probes. Which one is used at container startup, and which during container running? A DB check is probably OK at startup.

We may be able to avoid the DB hit in the middleware by whitelisting ``LANGUAGE_URL_IGNORED_PATHS``. It's been a while since I looked at ``DocumentZoneMiddleware``, I need to catch up.

**Comment by jwhitlock** [comment]
I didn't ready @escattone's comment closely, which answers my question:

* ``liveness`` - Is the application still running? If not, restart it.
* ``readiness`` - Is the application ready to serve traffic? If not, take it out of the service.

Kubernetes calls both while the application is running, and takes the programmed action. There's no high level logic like "huh I've just restarted half the applications, I should back off" by default.

This seems to be a relevant article, that suggests making probes as dumb as possible, unless you are 100% sure that you want Kubernetes to restart or unroute an application:

https://kubestuff.wordpress.com/2017/11/25/the-self-healing-myth-readiness-liveness-probes/

**Comment by jwhitlock** [comment]
More docs:

* https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/ - Docs
* https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#when-should-you-use-liveness-or-readiness-probes - Advice for when each is applicable
* https://www.ianlewis.org/en/using-kubernetes-health-checks - advises testing external services (DB, etc.) in readiness probes so that a strict startup order is not needed, mentions Kelsey Hightower's [12 Fractured Apps](https://medium.com/@kelseyhightower/12-fractured-apps-1080c73d481c).
* https://medium.com/spire-labs/utilizing-kubernetes-liveness-and-readiness-probes-to-automatically-recover-from-failure-2fe0314f2b2e - mentions readiness as a fix for slow-to-start services.

Here's our current settings:

| Setting | web | api | kumascript | celery-worker |
| --- | --- | --- | --- | --- |
|liveness ``initialDelaySeconds`` | 20 | 20 | 10 | N/A |
|liveness ``periodSeconds``       |  3 |  3 | 3 | N/A |
|liveness ``timeoutSeconds``     |  1 |  1 | 1 | N/A |
|liveness ``failureThreshold``  | 3 | 3 | 3 | N/A |
|readiness ``initialDelaySeconds`` | 20 | 20 | 10 | N/A |
|readiness ``periodSeconds``       |  3 |  3 | 3 | N/A |
|readiness ``timeoutSeconds``     |  1 |  1 | 1 | N/A |
|readiness ``successThreshold``  | 1 | 1 | 1 | N/A |
|readiness ``failureThreshold``  | 3 | 3 | 3 | N/A |
|gunicorn timeout | 120 | 120 | N/A | N/A |

The default of 1 second timeouts jumps out at me (and at @safwanrahman, initially). I think we can increase it  - 5 sec for readiness, 60 for liveness as a start?

I tried booting a new web container. The first log message was at 20:52:34, and the first request was served 6 seconds later at 20:52:40. This suggests that we may be able to lower the ``initialDelaySeconds`` to less than 20, but we can wait to tune than.

**Comment by safwanrahman** [comment]
I think we can remove the `initialDelaySeconds` from the `readiness`. So kubarnetes will check the status of the cluster  by calling the endpoint, and add the container to the network as soon as he gets the reply.
Currently, in theory, if all of our pods get down, there are no way to make it up before 20 seconds. So kubernetes will up the container, wait 20 seconds, make a `readiness` check, then route traffic there.

**Comment by jwhitlock** [comment]
After some discussion in IRC, we decided on some things:

We want to keep the ``readiness`` probe, and continue with the database check for now.  It appears readiness is important for rollouts without errors or downtime, and several people recommend checking external services in readiness probes, to avoid designing around service startup order.  Later, we may add a timeout to the Django database connection, so that we'll get an error rather than a Kubernetes probe timeout.  We may also adjust the Document Zone middleware, to avoid a database hit for probe endpoints.

We're not sure about the ``liveness`` endpoint, because we're not sure about cases when a restart is the right thing. For now, we want the application to first be taken out of service by the ``readiness`` failure, then later rebooted if it still can't recover.

We read [some Go code](https://github.com/kubernetes/kubernetes/blob/46c7ec209ab315656fc271708df46d266474d8f9/pkg/kubelet/prober/worker.go#L101-L105), and we think that the probe runs every ``periodSeconds``, not ``periodSeconds`` after the last probe completes. So, when an application is doomed, the action is taken in (``periodSeconds`` * ``failureThreshold`` + ``timeoutSeconds``) seconds. That's 28 seconds for readiness, 82 seconds for liveness.

The new proposed settings (changes in **bold**, @escattone is writing PR):

| Setting | web | api | kumascript | celery-worker |
| --- | --- | --- | --- | --- |
|liveness ``initialDelaySeconds`` | 20 | 20 | **20** | N/A |
|liveness ``periodSeconds``       |  **12** | **12** | **12** | N/A |
|liveness ``timeoutSeconds``     |  **10** | **10** | **10** | N/A |
|liveness ``failureThreshold``  | **6** | **6** | **6** | N/A |
|readiness ``initialDelaySeconds`` | **10** | **10** | 10 | N/A |
|readiness ``periodSeconds``       |  **6** | **6** | **6** | N/A |
|readiness ``timeoutSeconds``     |  **5** | **5** | **5** | N/A |
|readiness ``successThreshold``  | 1 | 1 | 1 | N/A |
|readiness ``failureThreshold``  | 3 | 3 | 3 | N/A |
|gunicorn timeout | 120 | 120 | N/A | N/A |

**Comment by escattone** [comment]
Very nice summary of our discussion, thanks @jwhitlock!
