### ISSUE TITLE
migrate MozMEAO apps to Oregon-b

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#705]
depends on https://github.com/mozmeao/infra/issues/697

**Comment by glogiotatidis** [comment]
I don't mean to disregard your efforts but I suggest that the owner of each app migrates to new clusters. I find my apps (snippets, snippets-stats, carreers) deployed with wrong / incomplete settings: some of them updated to the new clusters, some of them don't match the sister apps in other clusters, it's really confusing. 

I know ideally all those things they should be automated but since we're not there yet, it's better imho to have the app owners deploy to ensure that the app works OK. Otherwise we get a false sense that things are right (since app is deployed) while they are not (b/c settings are wrong).

**Comment by metadave** [comment]
> I find my apps (snippets, snippets-stats, carreers) deployed with wrong / incomplete settings: some of them updated to the new clusters, some of them don't match the sister apps in other clusters, it's really confusing.

I think the root problem here is that each app isn't fully documented (or the docs are out of date). I put in a ton of effort to capture anything config/infra related for each app in [this](https://github.com/mozmeao/infra/tree/master/apps) directory, but it can't be a one person effort to maintain. There's a lot of risk in having each owner be the only person who knows how to fully (and correctly) install an app. Only when the apps are documented, scripted and maintained in a [single location](https://github.com/mozmeao/infra/tree/master/apps) can we hope to achieve an automated solution.

**Comment by glogiotatidis** [comment]
> I find my apps (snippets, snippets-stats, carreers) deployed with wrong / incomplete settings: some of them updated to the new clusters, some of them don't match the sister apps in other clusters, it's really confusing.
> 
> I think the root problem here is that each app isn't fully documented (or the docs are out of date). I put in a ton of effort to capture anything config/infra related for each app in this directory, but it can't be a one person effort to maintain. There's a lot of risk in having each owner be the only person who knows how to fully (and correctly) install an app. Only when the apps are documented, scripted and maintained in a single location can we hope to achieve an automated solution.

Agree and I say the same things you say in the next paragraph of my first comment. I know you put a ton of effort and I appreciate that and we should continue that. What I'm suggesting is that until we get there, owner should deploy apps

**Comment by jgmize** [comment]
@glogiotatidis all of the apps deployed to oregon-b are very much a WIP. I had no intention of putting them into production without your (and @pmac's) help reviewing settings, validating functionality, etc. Apologies for any confusion.

**Comment by jgmize** [comment]
Migration complete.
