### ISSUE TITLE
Akamai performance testing (bedrock performance test suite to start)

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#935]

**Comment by metadave** [comment]
https://github.com/mozmeao/infra/issues/895

**Comment by jgmize** [comment]
Due to Akamai's lack of support for the "Vary: accept-language" header, none of the l10n redirects will be cached, which may have a significant negative impact on performance that will not show up on the test suites that measure individual pages, as every request that goes through an l10n redirect will have a non-trivial latency penalty.
